// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionsList: typeof import('./src/components/ActionsList.vue')['default']
    ButtonRepo: typeof import('./src/components/ButtonRepo.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CardItem: typeof import('./src/components/CardItem.vue')['default']
    Cards: typeof import('./src/components/Cards.vue')['default']
    DesktopNavigation: typeof import('./src/components/DesktopNavigation.vue')['default']
    MobileNavigation: typeof import('./src/components/MobileNavigation.vue')['default']
    NarrowSidebar: typeof import('./src/components/NarrowSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopNavigation: typeof import('./src/components/TopNavigation.vue')['default']
  }
}
